menu:
    Blog: /
    Archive: /archives/
    GitHub: https://github.com/jm00oo
    LinkedIn: https://www.linkedin.com/jhih-ming-huang-a8a58965/
    Rss: /atom.xml

favicon: https://avatars1.githubusercontent.com/jm00oo?v=3&s=466
logo: https://avatars1.githubusercontent.com/jm00oo?v=3&s=466

# Comment
# e.g disqus: seansun
disqus: jm00oo
duoshuo:
cloudTie:

# Analytics
# google-analytics:
ga: UA-67286515-1

# Copyright Infomation
startyear: 2017
